spring.application.name=AirbnbBooking

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/airbnb
spring.datasource.username=postgres
spring.datasource.password=Avijitroy2000
spring.datasource.driver-class-name=org.postgresql.Driver


# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Port
server.port=8087
